#ifndef CONSTANT_INDEX_C
#define CONSTANT_INDEX_C

// Tree Trie Definitions 
#define MAX_RESPONSE_LENGTH 1024 * 100
#define TRIE_CHILDREN_LENGTH 255
#define ADDRESS_LENGTH 16
#define PUBKEY_LENGTH 32

// Search Definitions
#define MAX_LIMIT_RESULTS 100
#define MAX_USERS_TO_VISIT 130000
#define MIN_SIMILARITY_TERM .55

// HTTP constantes definitions
#define HTTP_STATUS_OK 200
#define HTTP_STATUS_BAD_REQUEST 400
#define HTTP_STATUS_FORBIDDEN 403
#define HTTP_STATUS_NOT_FOUND 404
#define HTTP_STATUS_UNAUTHORIZED 401
#define HTTP_STATUS_INTERNAL_ERROR 500

#endif 



